// Generated by CoffeeScript 1.12.1
(function() {
  var a, b, c, n, test;

  c = 10;

  n = 8;

  a = "Хорошо";

  b = "Плохо";

  test = function() {
    if (c < n) {
      return console.log(a);
    } else {
      return console.log(b);
    }
  };

  test();

}).call(this);
